<?php

/**
 * @file
 * Implements Hooks functions
 */

/**
 * Implements hook_form_alter().
 * Function to disable form fields in Edit Form depending on the User Role.
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 * @return void
 */
function user_manager_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $cur_user = \Drupal::currentUser();
  $user_roles = $cur_user->getRoles();

  if (!in_array('administrator', $user_roles)) {
    if ($form_id == 'edit_users') {
      if (isset($form['username'])) {
        $form['username']['#disabled'] = true;
        $form['username']['#description'] = 'Only Admin Role can Edit this Field';
      }
    }
  }
}

/**
 * Implements hook_cron().
 * @return void
 */
/*function user_manager_cron() {
  $queue = Drupal::queue('delete_Users_Queue');
  $queueItem = $queue->claimItem();

  if ($queueItem) {
    $queue_worker = Drupal::service('plugin.manager.queue_worker')
      ->createInstance('delete_Users_Queue');
    $queue_worker->processItem($queueItem->data);
    $queue->deleteItem($queueItem);

  }

  $queue = Drupal::queue('user_pass_queue');
  $queueItem = $queue->claimItem();
  if ($queueItem) {
    $queue_worker = Drupal::service('plugin.manager.queue_worker')
      ->createInstance('user_pass_queue');
    $queue_worker->processItem($queueItem->data);
    $queue->deleteItem($queueItem);
  }

}*/
